// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfSockMeta struct {
	_             structs.HostLayout
	SynTs         uint64
	EstablishedTs uint64
}

type bpfTcpEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	DurationNs  uint64
	Saddr       [4]uint8
	Daddr       [4]uint8
	Sport       uint16
	Dport       uint16
	Family      uint16
	Oldstate    uint8
	Newstate    uint8
	EventType   uint8
	Pad         [7]uint8
	Comm        [16]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapEvents                 = "events"
	bpfMapSockStore              = "sock_store"
	bpfProgTraceInetSockSetState = "trace_inet_sock_set_state"
	bpfProgTraceTcpRetransmit    = "trace_tcp_retransmit"
	bpfVarUnused                 = "unused"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
	TraceTcpRetransmit    *ebpf.ProgramSpec `ebpf:"trace_tcp_retransmit"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events    *ebpf.MapSpec `ebpf:"events"`
	SockStore *ebpf.MapSpec `ebpf:"sock_store"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events    *ebpf.Map `ebpf:"events"`
	SockStore *ebpf.Map `ebpf:"sock_store"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.SockStore,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
	TraceTcpRetransmit    *ebpf.Program `ebpf:"trace_tcp_retransmit"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceInetSockSetState,
		p.TraceTcpRetransmit,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
